name: 'lighthouse-badges-generator'
description: 'Greet someone and record the time'
inputs:
  badgeStyle:
    description: 'Badge Style: plastic, flat, flat-square, for-the-badge or social'
    default: 'plastic'
  mdName:
    description: 'Name or file path to the MD file'
    default: 'README.md'
  url:
    description: 'URL to audit'
    required: true
  commitMessage:
    description: 'Commit message'
    default: '🚦 Add lighthouse bagdes!'
  commitAuthor:
    description: 'Commit author'
    default: 'lighthouse-bot'

outputs:
  time: # id of output
    description: 'The time we greeted you'
    value: string

runs:
  using: 'composite'
  steps:
    - name: checking out repo
      uses: actions/checkout@v3
    - run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      with:
        data_path: ${{ github.workspace }}
    # - name: Push
    #   shell: bash
    #   run: |
    #     git config --global user.name "${{ inputs.commitAuthor }}"
    #     git config --global user.email "lighthouse@bot.com"
    #     git commit -a -m "${{ inputs.commitMessage }}"
    #     git push
